[package]
name = "bitcoin-node"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32.5", features = ["rand-std"] }
bitcoinkernel = "0.0.15"
crossbeam-channel = "0.5.14"
ctrlc = "3.4.5"
dns-lookup = "2.0.4"
env_logger = "0.11.6"
log = "0.4.25"
